[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts",
    "@api3/airnode-protocol/=lib/airnode/packages/airnode-protocol/",
]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
gnosis = "${GNOSIS_RPC_URL}"

[etherscan]
sepolia = { key = "ETHERSCAN_SEPOLIA_KEY", url = "https://api-sepolia.etherscan.io/api" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
